export const CONFLICT = 'CONFLICT';
export const NOT_FOUND = 'NOT_FOUND';
export const PASSWORD_NOT_MATCH = 'PASSWORD_NOT_MATCH';
export const CAN_NOT_GET_FACEBOOK_TOKEN = 'CAN_NOT_GET_FACEBOOK_TOKEN';
export const CAN_NOT_VERIFY_FACEBOOK_TOKEN = 'CAN_NOT_VERIFY_FACEBOOK_TOKEN';
